# This is a basic workflow to help you get started with Actions

name: Create a new calendar image

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule but only for the main branch
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - name: Create calendar image
        run: |
          python calendar.py
      
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "fj.morenovazquez@ugto.mx"
          git config --global user.name "fcomovaz"
          git add -A
          git commit -m "Calendar Image Succesfully Created!" || exit 0
          git push
